# 作业 4：广播机制与向量化距离计算

In [3]:
import numpy as np

In [4]:
points_A = np.random.randint(0,101,(5,2))
points_B = np.random.randint(0,101,(8,2))


In [ ]:
xa=points_A[:,0].reshape(5,1)
ya=points_A[:,1].reshape(5,1)
xb=points_B[:,0].reshape(1,8)
yb=points_B[:,1].reshape(1,8)
sx=(xa-xb)**2
sy=(ya-yb)**2
s=np.around(np.sqrt(sx+sy),2)
print(s)
sAmin=np.min(s,axis=1)
sBmin=np.min(s,axis=0)
index=np.where(sBmin<20)
print('points_B 中与 points_A 中至少一个点的距离小于 20 的所有点的索引:',index)
print(sAmin)


[[ 10.82  11.66  33.54  61.2   14.32  88.2   75.    48.8 ]
 [ 88.1   72.95 108.9   50.8   93.91  93.09  10.    86.41]
 [ 58.26  53.71  34.53  47.38  59.4   46.87  89.89   8.6 ]
 [ 58.69  45.8   89.    59.06  64.38 103.47  27.07  81.02]
 [ 64.01  49.25  71.87  11.66  69.03  56.3   40.31  43.83]]
points_B 中，与 points_A 中至少一个点的距离小于 20 的所有点的索引: (array([0, 1, 3, 4, 6, 7]),)
[10.82 10.    8.6  27.07 11.66]


In [16]:
help(np.argmin)


Help on _ArrayFunctionDispatcher in module numpy:

argmin(a, axis=None, out=None, *, keepdims=<no value>)
    Returns the indices of the minimum values along an axis.

    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dimensions with size one. With this option,
        the result will broadcast correctly against the array.

        .. versionadded:: 1.22.0

    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed. If `keepdims` is set to True,
       