# 作业 5：图像数据的数组表示与操作

In [5]:
import numpy as np
grayscale_image=np.random.randint(0,256,(200,300))
sepia_matrix = np.array([
    [0.393, 0.769, 0.189],
    [0.349, 0.686, 0.168],
    [0.272, 0.534, 0.131]
])

In [17]:
image=np.stack([grayscale_image,grayscale_image,grayscale_image],axis=1)
image=np.clip(image, 0, 255, out=None)
print(image)


[[[ 12 229 241 ... 174  60  67]
  [ 12 229 241 ... 174  60  67]
  [ 12 229 241 ... 174  60  67]]

 [[ 16 121  26 ... 100 214  67]
  [ 16 121  26 ... 100 214  67]
  [ 16 121  26 ... 100 214  67]]

 [[ 81  88 156 ...  71  68  30]
  [ 81  88 156 ...  71  68  30]
  [ 81  88 156 ...  71  68  30]]

 ...

 [[148 152  29 ...  88 225  72]
  [148 152  29 ...  88 225  72]
  [148 152  29 ...  88 225  72]]

 [[165   9 122 ... 203  83  76]
  [165   9 122 ... 203  83  76]
  [165   9 122 ... 203  83  76]]

 [[ 91  18 172 ...  54  22 163]
  [ 91  18 172 ...  54  22 163]
  [ 91  18 172 ...  54  22 163]]]


In [18]:
sepia_image = np.clip(np.matmul(sepia_matrix,image),0,255)
print(sepia_image)

[[[ 16.212 255.    255.    ... 235.074  81.06   90.517]
  [ 14.436 255.    255.    ... 209.322  72.18   80.601]
  [ 11.244 214.573 225.817 ... 163.038  56.22   62.779]]

 [[ 21.616 163.471  35.126 ... 135.1   255.     90.517]
  [ 19.248 145.563  31.278 ... 120.3   255.     80.601]
  [ 14.992 113.377  24.362 ...  93.7   200.518  62.779]]

 [[109.431 118.888 210.756 ...  95.921  91.868  40.53 ]
  [ 97.443 105.864 187.668 ...  85.413  81.804  36.09 ]
  [ 75.897  82.456 146.172 ...  66.527  63.716  28.11 ]]

 ...

 [[199.948 205.352  39.179 ... 118.888 255.     97.272]
  [178.044 182.856  34.887 ... 105.864 255.     86.616]
  [138.676 142.424  27.173 ...  82.456 210.825  67.464]]

 [[222.915  12.159 164.822 ... 255.    112.133 102.676]
  [198.495  10.827 146.766 ... 244.209  99.849  91.428]
  [154.605   8.433 114.314 ... 190.211  77.771  71.212]]

 [[122.941  24.318 232.372 ...  72.954  29.722 220.213]
  [109.473  21.654 206.916 ...  64.962  26.466 196.089]
  [ 85.267  16.866 161.164 ...  

In [26]:
a=np.split(sepia_image,3,axis=1)
print(a)

[array([[[ 16.212, 255.   , 255.   , ..., 235.074,  81.06 ,  90.517]],

       [[ 21.616, 163.471,  35.126, ..., 135.1  , 255.   ,  90.517]],

       [[109.431, 118.888, 210.756, ...,  95.921,  91.868,  40.53 ]],

       ...,

       [[199.948, 205.352,  39.179, ..., 118.888, 255.   ,  97.272]],

       [[222.915,  12.159, 164.822, ..., 255.   , 112.133, 102.676]],

       [[122.941,  24.318, 232.372, ...,  72.954,  29.722, 220.213]]],
      shape=(200, 1, 300)), array([[[ 14.436, 255.   , 255.   , ..., 209.322,  72.18 ,  80.601]],

       [[ 19.248, 145.563,  31.278, ..., 120.3  , 255.   ,  80.601]],

       [[ 97.443, 105.864, 187.668, ...,  85.413,  81.804,  36.09 ]],

       ...,

       [[178.044, 182.856,  34.887, ..., 105.864, 255.   ,  86.616]],

       [[198.495,  10.827, 146.766, ..., 244.209,  99.849,  91.428]],

       [[109.473,  21.654, 206.916, ...,  64.962,  26.466, 196.089]]],
      shape=(200, 1, 300)), array([[[ 11.244, 214.573, 225.817, ..., 163.038,  56.22 ,  62.77